package com.bachatgat.model;

public enum TransactionType {
    SHARE_CONTRIBUTION,
    SHARE_COLLECTION,
    SHARE_LATE_FEE,
    LOAN_DISBURSEMENT,
    LOAN_PRINCIPAL_PAYMENT,
    LOAN_PRINCIPAL_REPAYMENT,
    LOAN_INTEREST_PAYMENT,
    LOAN_INTEREST_INCOME,
    LOAN_PENALTY_INCOME,
    LOAN_REPAYMENT,
    LOAN_EXTRA_PAYMENT,
    EXTRA_LOAN_PAYMENT,
    MEMBER_SAVING,
    LOAN_APPLICATION,
    LOAN_APPROVAL,
    LOAN_INTEREST,
    EXPENSE,
    OTHER_EXPENSE,
    OTHER_INCOME,
    MEMBER_INCOME_DISTRIBUTION,
    MEMBER_EXPENSE_DISTRIBUTION,
    BANK_DEPOSIT,
    BANK_WITHDRAWAL,
    ADJUSTMENT,
    REVERSAL,
    REFUND
}

